openapi: "3.0.0"
info:
  title: Argent Bank API V2 - Users Transactions
  description: Endpoints specs proposal for V2 features
  version: '2.0.0'
  termsOfService: 'http://swagger.io/terms/'
paths:
  "/user/accounts/{accountId}":
    get:
      security:
        - bearerAuth: []
      tags:
        - TxList
      parameters:
        - name: accountId
          in: path
          required: true
          content: { "application/json": { "schema": { "type": "string" } } }
      summary: Transactions list
      description: Fetch current month transactions list for {accountId}
      responses:
        '200':
          description: Fetched transactions list successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TxList'
        '400':
          description: Client request error
        '418':
          description: Server can't brew coffee because it's a teapot
        '500':
          description: Internal Server Error
  "/user/accounts/{accountId}/{TxHash}":
    get:
      security:
        - bearerAuth: []
      tags:
        - TxItem
      parameters:
        - name: accountId
          in: path
          required: true
          content: { "application/json": { "schema": { "type": "string" } } }
        - name: TxHash
          in: path
          required: true
          content: { "application/json": { "schema": { "type": "string" } } }
      summary: Transaction Item Details
      responses:
        '200':
          description: Fetched transactions list successfully
        '400':
          description: Client request error
        '500':
          description: Internal Server Error
    put:
      security:
        - bearerAuth: []
      tags:
        - TxItem
      parameters:
        - name: accountId
          in: path
          required: true
          content: { "application/json": { "schema": { "type": "string" } } }
        - name: TxHash
          in: path
          required: true
          content: { "application/json": { "schema": { "type": "string" } } }
        - name: Tx Details Payload
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/TxItem'
      summary: Transaction Item Details update
      responses:
        '200':
          description: Updated transaction details successfully
        '400':
          description: Client request error
        '500':
          description: Internal Server Error
    delete:
      security:
        - bearerAuth: []
      tags:
        - TxItem
      parameters:
        - name: accountId
          in: path
          required: true
          content: { "application/json": { "schema": { "type": "string" } } }
        - name: TxHash
          in: path
          required: true
          content: { "application/json": { "schema": { "type": "string" } } }
      summary: Transaction Item Details delete
      responses:
        '200':
          description: Deleted transaction details successfully
        '400':
          description: Client request error
        '500':
          description: Internal Server Error
components:
  securitySchemes:
    bearerAuth:
      type: http
      description: JWT Token authorization
      scheme: bearer
      bearerFormat: JWT
  schemas:
    TxList:
      type: object
      properties:
        accountId:
          type: string
          description: Account ID
          example: '0x1234567890123456789012345678901234567890'
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/TxItem'
        categories:
          type: array
          items:
            type: string
            description: Transaction category
            example: 'Food'
    TxItem:
      type: object
      properties:
        hash:
          type: string
          description: Transaction hash
          example: '0x1234567890123456789012345678901234567890'
        category:
          type: string
          description: Transaction category
          example: 'Food'
        notes:
          type: string
          description: Transaction notes
          example: 'Pizza'